services:
  db:
    image: postgres
    container_name: unrowdy_pg
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 5s
      retries: 5
  backend:
    tty: true
    container_name: unrowdy_backend
    build:
      context: ./backend
    env_file:
      - .env
      - backend/.env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /app/.venv
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - .venv/
        - action: rebuild
          path: ./pyproject.toml
  frontend:
    tty: true
    container_name: unrowdy_frontend
    build:
      context: ./frontend
    env_file:
      - frontend/.env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "80:80"
    volumes:
      - ./frontend:/app
      - /app/.venv
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - .venv/
        - action: rebuild
          path: ./pyproject.toml
volumes:
  db_data:
